spring.application.name=employee

# employee_db
spring.datasource.employee.url=jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=UTC
spring.datasource.employee.username=root
spring.datasource.employee.password=
spring.datasource.employee.driver-class-name=com.mysql.cj.jdbc.Driver

# salary_db
spring.datasource.salary.url=jdbc:mysql://localhost:3306/salary_db?useSSL=false&serverTimezone=UTC
spring.datasource.salary.username=root
spring.datasource.salary.password=
spring.datasource.salary.driver-class-name=com.mysql.cj.jdbc.Driver

# attendance_db
spring.datasource.attendance.url=jdbc:mysql://localhost:3306/attendance_db?useSSL=false&serverTimezone=UTC
spring.datasource.attendance.username=root
spring.datasource.attendance.password=
spring.datasource.attendance.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA chung
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8888

logging.level.root=INFO
logging.level.com.example.demo=DEBUG

jwt.secret=your-super-secret-key-at-least-32-chars

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/api/v1/auth/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

