spring:
  application:
    name: employee

  datasource:
   employee:
      url: jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  salary:
      url: jdbc:mysql://localhost:3306/salary_db?useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  attendance:
      url: jdbc:mysql://localhost:3306/attendance_db?useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      open-in-view: false
  jwt:
  secret: your-super-secret-key-at-least-32-chars

server:
  port: 8888

logging:
  level:
    root: INFO
    com.example.demo: DEBUG